.TH "BJ_S.Sabot" 3 "Mon Jun 8 2020" "Version Alpha" "Black Jack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BJ_S.Sabot
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSabot\fP ()"
.br
.ti -1c
.RI "\fBCartes\fP \fBCarteDessus\fP ()"
.br
.RI "Simule la carte du dessus en sortant une carte aléatoire du sabot\&. "
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBPaquets\fP[] \fBsabot\fP"
.br
.ti -1c
.RI "int \fBnbPaquets\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 5 of file Sabot\&.cs\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BJ_S\&.Sabot\&.Sabot ()\fC [inline]\fP"

.PP
Definition at line 10 of file Sabot\&.cs\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCartes\fP BJ_S\&.Sabot\&.CarteDessus ()\fC [inline]\fP"

.PP
Simule la carte du dessus en sortant une carte aléatoire du sabot\&. Lorsqu'un paquet est vide le remplace par le dernier paquet valide et reduit le compte de paquet
.PP
\fBReturns\fP
.RS 4
\fBCartes\fP : Aléatoire
.RE
.PP

.PP
Definition at line 25 of file Sabot\&.cs\&.
.SH "Member Data Documentation"
.PP 
.SS "int BJ_S\&.Sabot\&.nbPaquets\fC [private]\fP"

.PP
Definition at line 8 of file Sabot\&.cs\&.
.SS "\fBPaquets\fP [] BJ_S\&.Sabot\&.sabot\fC [private]\fP"

.PP
Definition at line 7 of file Sabot\&.cs\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Black Jack from the source code\&.
