.TH "BJ_S" 3 "Mon Jun 8 2020" "Version Alpha" "Black Jack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BJ_S
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBProperties\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAI\fP"
.br
.ti -1c
.RI "class \fBBlackuJacku\fP"
.br
.ti -1c
.RI "class \fBCartes\fP"
.br
.ti -1c
.RI "class \fBConnexions\fP"
.br
.RI "Classe gérant la connectivité entre plusieurs joueurs\&. "
.ti -1c
.RI "class \fBCroupier\fP"
.br
.ti -1c
.RI "class \fBJoueurs\fP"
.br
.ti -1c
.RI "class \fBMains\fP"
.br
.ti -1c
.RI "class \fBMenu\fP"
.br
.RI "\fBMenu\fP Principal "
.ti -1c
.RI "class \fBMise\fP"
.br
.ti -1c
.RI "class \fBNomDeJoueur\fP"
.br
.RI "Demande le nom du joueur pour créer un partie\&. "
.ti -1c
.RI "class \fBPaquets\fP"
.br
.ti -1c
.RI "class \fBPartie\fP"
.br
.ti -1c
.RI "class \fBSabot\fP"
.br
.ti -1c
.RI "class \fBUI\fP"
.br
.RI "Affiche et gère les actions de l'utilisateur pour le déroulement de la partie\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Black Jack from the source code\&.
