.TH "BJ_S.Properties" 3 "Mon Jun 8 2020" "Version Alpha" "Black Jack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BJ_S.Properties
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBResources\fP"
.br
.RI "A strongly-typed resource class, for looking up localized strings, etc\&. "
.ti -1c
.RI "class \fBSettings\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Black Jack from the source code\&.
