.TH "Menu.Designer.cs" 3 "Mon Jun 8 2020" "Version Alpha" "Black Jack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Menu.Designer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBJ_S\&.Menu\fP"
.br
.RI "\fBMenu\fP Principal "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBJ_S\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Black Jack from the source code\&.
