.TH "doc/ProtocolBJ.txt" 3 "Mon Jun 8 2020" "Version Alpha" "Black Jack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
doc/ProtocolBJ.txt
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "Connection \fB__pad0__\fP"
.br
.ti -1c
.RI "Connection \fBMIN\fP"
.br
.ti -1c
.RI "Connection \fBMAX\fP"
.br
.ti -1c
.RI "Connection \fBCASH\fP"
.br
.ti -1c
.RI "Connection NbJoueurs Le client envois son nom Attend le nom des autres \fBRecoit\fP \fBJoueur1\fP"
.br
.ti -1c
.RI "Connection NbJoueurs Le client envois son nom Attend le nom des autres \fBRecoit\fP \fBJoueur2\fP"
.br
.ti -1c
.RI "Connection NbJoueurs Le client envois son nom Attend le nom des autres Recoit Joueur3 Attend l init de la game \fBRecoit\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "Connection __pad0__"

.PP
Definition at line 7 of file ProtocolBJ\&.txt\&.
.SS "Connection CASH"

.PP
Definition at line 7 of file ProtocolBJ\&.txt\&.
.SS "Connection NbJoueurs Le client envois son nom Attend le nom des autres \fBRecoit\fP Joueur1"

.PP
Definition at line 10 of file ProtocolBJ\&.txt\&.
.SS "Connection NbJoueurs Le client envois son nom Attend le nom des autres \fBRecoit\fP Joueur2"

.PP
Definition at line 10 of file ProtocolBJ\&.txt\&.
.SS "Connection MAX"

.PP
Definition at line 7 of file ProtocolBJ\&.txt\&.
.SS "Connection MIN"

.PP
Definition at line 7 of file ProtocolBJ\&.txt\&.
.SS "Connection NbJoueurs Le client envois son nom Attend le nom des autres Recoit Joueur3 Attend l init de la game Recoit"

.PP
Definition at line 12 of file ProtocolBJ\&.txt\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Black Jack from the source code\&.
