.TH "UI.Designer.cs" 3 "Mon Jun 8 2020" "Version Alpha" "Black Jack" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UI.Designer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBJ_S\&.UI\fP"
.br
.RI "Affiche et gère les actions de l'utilisateur pour le déroulement de la partie\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBBJ_S\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Black Jack from the source code\&.
